#下面这些内容是为了让MyBatis映射
mybatis:
  #指定Mybatis的Mapper文件
  mapper-locations: classpath:mappers/*xml
  #指定Mybatis的实体目录
  type-aliases-package: com.itheima.mybatis.entity
  configuration:
    #配置mybatis的日志，输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #mybatis驼峰命名自动映射开关
    map-underscore-to-camel-case: true
spring:
  datasource:
    #驱动类名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库链接地址
    url: jdbc:mysql://localhost:3306/waweb
    #连接数据库用户名
    username: root
    #连接数据库密码
    password: aaaa
  servlet:
    multipart:
      #单个文件最大上传大小
      max-file-size: 10MB
      #单个请求最大大小(一次请求可以上传多个文件)
      max-request-size: 100MB
#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug